## 2D scoring by Itay
get_controls <- function(counts, gene.list, verbose=F, control.genes.per.gene=10)
{
    # Itay: "Such scores are inevitably correlated with cell complexity so to avoid 
    # that I subtract a "control" score which is generated by averaging over a control 
    # gene set. Control gene sets are chosen to contain 100 times more genes than the 
    # real gene set (analogous to averaging over 100 control sets of similar size) and 
    # to have the same distribution of population/bulk - based expression levels as the 
    # real gene set, such that they are expected to have the same number of "zeros" and 
    # to eliminate the correlation with complexity."
    # ---------------------------------------------------------------------------------
    # Going to find control points by finding the closest genes in terms of expression level and % of the time we observe it
    if(verbose){cat(sprintf("Finding %s background genes based on similarity to given gene set [%s genes] \n", 
                            control.genes.per.gene*length(gene.list), length(gene.list)))}
    cat("Summarizing data \n")
    summary = data.frame(gene=row.names(counts), mean.expr = Matrix::rowMeans(counts), fract.zero = Matrix::rowMeans(counts==0), stringsAsFactors = F)
    #summary = data.frame(gene=row.names(counts), mean.expr = apply(counts,1,mean), fract.zero = apply(counts==0,1,mean), stringsAsFactors = F)
    summary$mean.expr.s = scale(summary$mean.expr)
    summary$fract.zero.s = scale(summary$fract.zero)
    actual.genes = summary[summary$gene %in% gene.list,]
    background.genes = summary[!summary$gene %in% gene.list,]
    
    #find the 10 closest genes to each cell cycle marker gene and add them to the lists of control genes
    get_closest_genes <- function(i)
    {
        background.genes$dist = sqrt((background.genes$mean.expr.s - actual.genes$mean.expr.s[i])^2 + 
                                         (background.genes$fract.zero.s - actual.genes$fract.zero.s[i])^2)
        ordered = background.genes$gene[order(background.genes$dist)]
        ordered = ordered[!ordered %in% controls] # don't take genes that already appear in the list 
        closest = head(ordered, n=control.genes.per.gene)
        return(closest)
    }
    controls = c();
    
    for (i in 1:length(gene.list)){
        #info(sprintf("Finding %s control genes for %s", control.genes.per.gene, gene.list[i]))
        closest = get_closest_genes(i)
        #info(sprintf("Found %s: ", length(closest)))
        controls = unique(c(controls, closest))
    }
    
    if(verbose){cat(sprintf("Control gene selection complete. %s genes found. \n", length(controls)))}
    #print(controls)
    return(controls)
}

## input gene filter
input_gene_filter <- function(mtx, gene_input){
    gene_mtx <- mtx %>% 
        rownames_to_column("gene") %>% 
        filter(gene %in% gene_input) %>% 
        column_to_rownames("gene")
    gene_output <- rownames(gene_mtx)
    gene_output <- gene_output[rowSums(gene_mtx>0) >= 10]
    return(gene_output)
}

## normalized count matrix
normalized_matrix <- as.data.frame(gcb_np_integrated[['RNA']]@data)

## Cell cycle
## G1S
g1s_gene <- c("Cdca7", "Mcm4", "Mcm2", "Rfc2", "Ung", "Mcm6", "Rrm1", "Slbp", 
              "Pcna", "Atad2", "Tipin", "Mcm5", "Uhrf1", "Rpa2", "Dtl", "Prim1", 
              "Fen1", "Hells", "Gmnn", "Pold3", "Nasp", "Chaf1b", "Gins2", "Pola1", 
              "Msh2", "Casp8ap2", "Cdc6", "Ubr7", "Ccne2", "Wdr76", "Tyms", "Cdc45", 
              "Clspn", "Rrm2", "Dscc1", "Rad51", "Usp1", "Exo1", "Blm", "Rad51ap1", 
              "Mlf1ip", "E2f8", "Brip1")
g1s_ctrl <- get_controls(counts = normalized_matrix,
                         gene.list = g1s_gene)
g1s_score <- colMeans(normalized_matrix[g1s_gene, ], na.rm = T)-colMeans(normalized_matrix[g1s_ctrl, ], na.rm = T)
gcb_np_integrated <- AddMetaData(gcb_np_integrated,
                                 g1s_score,
                                 "g1s_score")

gcb_np_integrated@meta.data %>%
    filter(seurat_clusters!=6) %>% 
    ggplot(aes(seurat_clusters, g1s_score, color = seurat_clusters)) +
    geom_violin(draw_quantiles=c(0.25,0.75),trim = FALSE) +
    geom_quasirandom(size = 0.01, width = 0.2, alpha = 0.3) +
    stat_summary(fun.y=mean, geom="point", shape=18, size=3, color="black") +
    theme(panel.grid.major = element_blank(), 
          panel.grid.minor = element_blank(), 
          panel.background = element_blank(), 
          panel.border = element_rect(fill = NA))
pairwise.t.test(gcb_np_integrated$g1s_score[gcb_np_integrated$seurat_clusters!=6], 
                gcb_np_integrated$seurat_clusters[gcb_np_integrated$seurat_clusters!=6], 
                p.adjust.method = "BH")
pairwise_t_test(gcb_np_integrated@meta.data[gcb_np_integrated$seurat_clusters!=6, ], 
                g1s_score~seurat_clusters, 
                p.adjust.method = "BH")

## G2M
g2m_gene <- c("Cbx5", "Aurkb", "Cks1b", "Cks2", "Hn1", "Hmgb2", "Anp32e", "Lbr", 
              "Tmpo", "Top2a", "Tacc3", "Tubb4b", "Ncapd2", "Rangap1", "Cdk1", 
              "Smc4", "Kif20b", "Cdca8", "Ckap2", "Ndc80", "Dlgap5", "Hjurp", 
              "Ckap5", "Bub1", "Ckap2l", "Ect2", "Kif11", "Birc5", "Cdca2", 
              "Nuf2", "Cdca3", "Nusap1", "Ttk", "Aurka", "Mki67", "Fam64a", 
              "Ccnb2", "Tpx2", "Anln", "Kif2c", "Cenpe", "Gtse1", 
              "Kif23", "Cdc20", "Ube2c", "Cenpf", "Cenpa", "Hmmr", "Ctcf", 
              "Psrc1", "Cdc25c", "Nek2", "Gas2l3", "G2e3")
g2m_ctrl <- get_controls(counts = normalized_matrix,
                         gene.list = g2m_gene)
g2m_score <- colMeans(normalized_matrix[g2m_gene, ], na.rm = T)-colMeans(normalized_matrix[g2m_ctrl, ], na.rm = T)
gcb_np_integrated <- AddMetaData(gcb_np_integrated,
                                 g2m_score,
                                 "g2m_score")

gcb_np_integrated@meta.data %>%
    filter(seurat_clusters!=6) %>% 
    ggplot(aes(seurat_clusters, g2m_score, color = seurat_clusters)) +
    geom_violin(draw_quantiles=c(0.25,0.75), trim = FALSE) +
    geom_quasirandom(size = 0.01, width = 0.2, alpha = 0.3) +
    stat_summary(fun.y=mean, geom="point", shape=18, size=3, color="black") +
    theme(panel.grid.major = element_blank(), 
          panel.grid.minor = element_blank(), 
          panel.background = element_blank(), 
          panel.border = element_rect(fill = NA))
pairwise.t.test(gcb_np_integrated$g2m_score[gcb_np_integrated$seurat_clusters!=6], 
                gcb_np_integrated$seurat_clusters[gcb_np_integrated$seurat_clusters!=6], 
                p.adjust.method = "BH")

## cell cylce
gcb_np_integrated@meta.data %>%
    filter(seurat_clusters!=6) %>% 
    ggplot(aes(g1s_score, g2m_score, color = seurat_clusters)) +
    geom_point(size = 0.01, show.legend = FALSE) +
    facet_wrap(~seurat_clusters, nrow = 1) +
    lims(x=c(-0.45, 1.3), y=c(-0.45, 1.3)) +
    theme(panel.grid.major = element_blank(), 
          panel.grid.minor = element_blank(), 
          panel.background = element_blank(), 
          panel.border = element_rect(fill = NA)) +
    xlab("G1/S phase") +
    ylab("G2/M phase") +
    coord_equal(ratio = 1)

## LZ and DZ
## LZ
lz_gene <- c("Egr2", "Ccnd2", "Egr1", "Plscr1", "Socs3", "Lifr", "Il4i1", 
             "Bcl2a1a", "Bcl2a1b", "Bcl2a1d", "Ccr6", "Cd83", "Hhex", "S1pr3", 
             "9630010G10Rik", "Dock10", "Hivep3", "Samsn1", "Myc", "Irf4", 
             "Gimap4", "Gpr183", "Cd69", "Ptger4", "Marcks", "Fscn1", "Ier2", 
             "Snn", "Bhlhe40", "Nfkbia", "Slpi", "Ifi30", "Pus7", "Matr3", 
             "Fam55b", "Cd86", "Rapgef4", "Rilpl2", "Gadd45g", "Cfp", "Slamf1", 
             "Tyms", "Cd40", "Mdn1", "C920008N22Rik")
lz_ctrl <- get_controls(counts = normalized_matrix,
                         gene.list = lz_gene)
lz_score <- colMeans(normalized_matrix[lz_gene, ], na.rm = T)-colMeans(normalized_matrix[lz_ctrl, ], na.rm = T)
gcb_np_integrated <- AddMetaData(gcb_np_integrated,
                                 lz_score,
                                 "lz_score")

gcb_np_integrated@meta.data %>%
    filter(seurat_clusters!=6) %>% 
    ggplot(aes(seurat_clusters, lz_score, color = seurat_clusters)) +
    geom_violin(draw_quantiles=c(0.25,0.75), trim = FALSE) +
    geom_quasirandom(size = 0.01, width = 0.2, alpha = 0.3) +
    stat_summary(fun.y=mean, geom="point", shape=18, size=3, color="black") +
    theme(panel.grid.major = element_blank(), 
          panel.grid.minor = element_blank(), 
          panel.background = element_blank(), 
          panel.border = element_rect(fill = NA))
pairwise.t.test(gcb_np_integrated$lz_score[gcb_np_integrated$seurat_clusters!=6], 
                gcb_np_integrated$seurat_clusters[gcb_np_integrated$seurat_clusters!=6], 
                p.adjust.method = "BH")

## DZ
dz_gene <- c("1190002H23Rik", "Pif1", "Otub2", "Psrc1", "Lrrc49", "Ccnb2", "Mnd1",
             "Lgr5", "Adhfe1", "Pafah1b3", "Hmmr", "Tifa", "Reln", "OTTMUSG00000016644",
             "Sepp1", "Cdkn3", "Gcnt3", "Cdc20", "Ube2c", "A630023P12Rik", "Serinc5",
             "Cenpa", "Ccnb1", "Gcet2", "Plk1", "Cenpf", "Tgfa", "Tpx2", "Depdc1b",
             "Gpd1l", "Polh", "Cep55", "Nek2", "Zkscan16", "Lmo4", "1810010H24Rik",
             "Gas2l3", "Ptgr1", "Aspm", "Rnf125", "Cxcr4", "Kif20a", "1700097N02Rik",
             "Kif2c", "A130040M12Rik", "E130306D19Rik", "Rabgap1l", "Bub1",
             "4930547N16Rik", "C730049O14Rik", "Nebl", "Lig4", "Neil1", "Pde2a",
             "Ehf", "Racgap1", "8430410A17Rik", "Cdca8", "Cdc14b", "Cdc25c", "Lipc",
             "Mprip", "Aurka", "Gpsm2", "Spdya", "Akap12", "Kif22", "Birc5",
             "Pfn2", "Ddx19a", "D2Ertd750e", "OTTMUSG00000015563", "D18Ertd653e")
dz_ctrl <- get_controls(counts = normalized_matrix,
                        gene.list = dz_gene)
dz_score <- colMeans(normalized_matrix[dz_gene, ], na.rm = T)-colMeans(normalized_matrix[dz_ctrl, ], na.rm = T)
gcb_np_integrated <- AddMetaData(gcb_np_integrated,
                                 dz_score,
                                 "dz_score")

gcb_np_integrated@meta.data %>%
    filter(seurat_clusters!=6) %>% 
    ggplot(aes(seurat_clusters, dz_score, color = seurat_clusters)) +
    geom_violin(draw_quantiles=c(0.25,0.75), trim = FALSE) +
    geom_quasirandom(size = 0.01, width = 0.2, alpha = 0.3) +
    stat_summary(fun.y=mean, geom="point", shape=18, size=3, color="black") +
    theme(panel.grid.major = element_blank(), 
          panel.grid.minor = element_blank(), 
          panel.background = element_blank(), 
          panel.border = element_rect(fill = NA))
pairwise.t.test(gcb_np_integrated$dz_score[gcb_np_integrated$seurat_clusters!=6], 
                gcb_np_integrated$seurat_clusters[gcb_np_integrated$seurat_clusters!=6], 
                p.adjust.method = "BH")

## Zone
gcb_np_integrated@meta.data %>%
    filter(seurat_clusters!=6) %>% 
    ggplot(aes(lz_score, dz_score, color = seurat_clusters)) +
    geom_point(size = 0.01, show.legend = FALSE) +
    facet_wrap(~seurat_clusters, nrow = 1) +
    lims(x=c(-0.3, 1), y=c(-0.3, 1)) +
    theme(panel.grid.major = element_blank(), 
          panel.grid.minor = element_blank(), 
          panel.background = element_blank(), 
          panel.border = element_rect(fill = NA)) +
    xlab("Light Zone (LZ)") +
    ylab("Dark Zone (DZ)") +
    coord_equal(ratio = 1)

## correlation between dz and lz, g2m and g1s
gcb_np_integrated@meta.data %>% 
    filter(seurat_clusters!=6) %>%
    group_by(seurat_clusters) %>% 
    summarise(lz_score = mean(lz_score),
              dz_score = mean(dz_score)) %>% 
    ggplot(aes(lz_score, dz_score, color = seurat_clusters)) +
    geom_point() +
    lims(x=c(-0.1, 0.2), y=c(-0.1, 0.4)) +
    theme_classic()

gcb_np_integrated@meta.data %>% 
    filter(seurat_clusters!=6) %>%
    group_by(seurat_clusters) %>% 
    summarise(g1s_score = mean(g1s_score),
              g2m_score = mean(g2m_score)) %>% 
    ggplot(aes(g1s_score, g2m_score, color = seurat_clusters)) +
    geom_point() +
    coord_equal() +
    theme_classic()

## GZ
gz_gene <- read.csv("signature_gene/gz_gene.csv", header = TRUE, stringsAsFactors = FALSE)
gz_gene <- unique(gz_gene$Gene)
gz_gene_filtered <- input_gene_filter(normalized_matrix, gz_gene)
gz_ctrl <- get_controls(counts = normalized_matrix,
                        gene.list = gz_gene_filtered)
gz_score <- colMeans(normalized_matrix[gz_gene_filtered, ], na.rm = T)-colMeans(normalized_matrix[gz_ctrl, ], na.rm = T)
gcb_np_integrated <- AddMetaData(gcb_np_integrated,
                                 gz_score,
                                 "gz_score")
gcb_np_integrated@meta.data %>%
    filter(seurat_clusters!=6) %>% 
    ggplot(aes(seurat_clusters, gz_score, color = seurat_clusters)) +
    geom_violin(draw_quantiles=c(0.25,0.75), trim = FALSE) +
    geom_quasirandom(size = 0.01, width = 0.2, alpha = 0.3) +
    stat_summary(fun.y=mean, geom="point", shape=18, size=3, color="black") +
    theme(panel.grid.major = element_blank(), 
          panel.grid.minor = element_blank(), 
          panel.background = element_blank(), 
          panel.border = element_rect(fill = NA))
pairwise.t.test(gcb_np_integrated$gz_score[gcb_np_integrated$seurat_clusters!=6], 
                gcb_np_integrated$seurat_clusters[gcb_np_integrated$seurat_clusters!=6], 
                p.adjust.method = "BH")

########
## Signature score by affinity
## oxidative phosphrylation
oxp_gene <- read.csv("signature_gene/oxp_gene.csv", header = TRUE, stringsAsFactors = FALSE)
oxp_gene <- oxp_gene$Gene
oxp_ctrl <- get_controls(counts = normalized_matrix,
                         gene.list = oxp_gene)
oxp_score <- colMeans(normalized_matrix[oxp_gene, ], na.rm = T)-colMeans(normalized_matrix[oxp_ctrl, ], na.rm = T)
gcb_np_integrated <- AddMetaData(gcb_np_integrated,
                                  oxp_score,
                                  "oxp_score")
gcb_np_integrated@meta.data %>%
    filter(affinity %in% c("High_affinity", "Low_affinity")) %>%
    mutate(affinity=factor(affinity, levels = c("Low_affinity", "High_affinity"))) %>% 
    ggplot(aes(affinity, oxp_score, color = affinity)) +
    geom_boxplot(size=1) +
    scale_color_manual(values = c("#3C5488FF", "#E64B35FF")) +
    theme(panel.background = element_rect(fill = "white"),
          axis.line = element_line(colour = "black"),
          axis.ticks.x = element_line(size = 1))

t.test(oxp_score~affinity, gcb_np_integrated@meta.data %>% filter(affinity %in% c("High_affinity", "Low_affinity")))

## glycolysis
glycolysis_gene <- read.csv("signature_gene/glycolysis_gene.csv", header = TRUE, stringsAsFactors = FALSE)
glycolysis_gene <- glycolysis_gene$Gene
glycolysis_ctrl <- get_controls(counts = normalized_matrix,
                                gene.list = glycolysis_gene)
glycolysis_score <- colMeans(normalized_matrix[glycolysis_gene, ], na.rm = T)-colMeans(normalized_matrix[glycolysis_ctrl, ], na.rm = T)
gcb_np_integrated <- AddMetaData(gcb_np_integrated,
                                 glycolysis_score,
                                 "glycolysis_score")
gcb_np_integrated@meta.data %>%
    filter(affinity %in% c("High_affinity", "Low_affinity")) %>%
    mutate(affinity=factor(affinity, levels = c("Low_affinity", "High_affinity"))) %>% 
    ggplot(aes(affinity, glycolysis_score, color = affinity)) +
    geom_boxplot(size=1) +
    scale_color_manual(values = c("#3C5488FF", "#E64B35FF")) +
    theme(panel.background = element_rect(fill = "white"),
          axis.line = element_line(colour = "black"),
          axis.ticks.x = element_line(size = 1))

t.test(glycolysis_score~affinity, gcb_np_integrated@meta.data %>% filter(affinity %in% c("High_affinity", "Low_affinity")))

## oxp vs glycolysis
gcb_np_integrated@meta.data %>%
    filter(seurat_clusters!=6) %>% 
    ggplot(aes(oxp_score, glycolysis_score, color = seurat_clusters)) +
    geom_point(size = 0.01, show.legend = FALSE) +
    facet_wrap(~seurat_clusters, nrow = 1) +
    lims(x=c(-0.35, 0.55), y=c(-0.35, 0.55)) +
    theme(panel.grid.major = element_blank(), 
          panel.grid.minor = element_blank(), 
          panel.background = element_blank(), 
          panel.border = element_rect(fill = NA)) +
    coord_equal(ratio = 1)

gcb_np_integrated@meta.data %>% 
    filter(seurat_clusters!=6) %>%
    group_by(seurat_clusters) %>% 
    summarise(oxp_score = mean(oxp_score),
              glycolysis_score = mean(glycolysis_score)) %>% 
    ggplot(aes(oxp_score, glycolysis_score, color = seurat_clusters)) +
    geom_point() +
    theme_classic()

gcb_np_integrated@meta.data %>%
    filter(seurat_clusters!=6) %>% 
    mutate(oxp_to_glycolysis = oxp_score/glycolysis_score,
           oxp_to_glycolysis2 = ifelse(oxp_to_glycolysis<5, oxp_to_glycolysis, 5),
           oxp_to_glycolysis2 = ifelse(oxp_to_glycolysis2>-5, oxp_to_glycolysis2, -5),
           finite = ifelse(abs(oxp_to_glycolysis)<5, "normal", "outlier")) %>% 
    ggplot(aes(seurat_clusters, oxp_to_glycolysis2, color = seurat_clusters)) +
    geom_violin(draw_quantiles=c(0.25,0.75)) +
    geom_quasirandom(aes(shape = finite), size = 0.01, width = 0.3, alpha = 0.5) +
    stat_summary(fun.y=mean, geom="point", shape=18, size=3, color="black") +
    scale_shape_manual(values = c(16, 17)) +
    theme(panel.grid.major = element_blank(), 
          panel.grid.minor = element_blank(), 
          panel.background = element_blank(), 
          panel.border = element_rect(fill = NA)) 
fit <- aov(oxp_to_glycolysis ~ seurat_clusters, gcb_np_integrated@meta.data %>%
               filter(seurat_clusters!=6) %>% 
               mutate(oxp_to_glycolysis = oxp_score/glycolysis_score))
TukeyHSD(fit)

## fatty acid beta oxidation
fatty_acid_beta_oxidation_gene <- read.csv("signature_gene/fatty_acid_beta_oxidation_gene.csv", header = TRUE, stringsAsFactors = FALSE)
fatty_acid_beta_oxidation_gene <- fatty_acid_beta_oxidation_gene$Gene
fatty_acid_beta_oxidation_ctrl <- get_controls(counts = normalized_matrix,
                                               gene.list = fatty_acid_beta_oxidation_gene)
fatty_acid_beta_oxidation_score <- colMeans(normalized_matrix[fatty_acid_beta_oxidation_gene, ], na.rm = T)-colMeans(normalized_matrix[fatty_acid_beta_oxidation_ctrl, ], na.rm = T)
gcb_np_integrated <- AddMetaData(gcb_np_integrated,
                                  fatty_acid_beta_oxidation_score,
                                  "fatty_acid_beta_oxidation_score")
gcb_np_integrated@meta.data %>%
    filter(affinity %in% c("High_affinity", "Low_affinity")) %>%
    mutate(affinity=factor(affinity, levels = c("Low_affinity", "High_affinity"))) %>%
    ggplot(aes(affinity, fatty_acid_beta_oxidation_score, color = affinity)) +
    geom_boxplot(size=1) +
    scale_color_manual(values = c("#3C5488FF", "#E64B35FF")) +
    theme(panel.background = element_rect(fill = "white"),
          axis.line = element_line(colour = "black"),
          axis.ticks.x = element_line(size = 1))
t.test(fatty_acid_beta_oxidation_score~affinity, gcb_np_integrated@meta.data %>% filter(affinity %in% c("High_affinity", "Low_affinity")))

## fatty acid omega oxidation
fatty_acid_omega_oxidation_gene <- read.csv("signature_gene/fatty_acid_omega_oxidation_gene.csv", header = TRUE, stringsAsFactors = FALSE)
fatty_acid_omega_oxidation_gene <- fatty_acid_omega_oxidation_gene$Gene
fatty_acid_omega_oxidation_ctrl <- get_controls(counts = normalized_matrix,
                                                gene.list = fatty_acid_omega_oxidation_gene)
fatty_acid_omega_oxidation_score <- colMeans(normalized_matrix[fatty_acid_omega_oxidation_gene, ], na.rm = T)-colMeans(normalized_matrix[fatty_acid_omega_oxidation_ctrl, ], na.rm = T)
gcb_np_integrated <- AddMetaData(gcb_np_integrated,
                                  fatty_acid_omega_oxidation_score,
                                  "fatty_acid_omega_oxidation_score")
gcb_np_integrated@meta.data %>%
    filter(affinity %in% c("High_affinity", "Low_affinity")) %>%
    mutate(affinity=factor(affinity, levels = c("Low_affinity", "High_affinity"))) %>%
    ggplot(aes(affinity, fatty_acid_omega_oxidation_score, color = affinity)) +
    geom_boxplot(size=1) +
    scale_color_manual(values = c("#3C5488FF", "#E64B35FF")) +
    theme(panel.background = element_rect(fill = "white"),
          axis.line = element_line(colour = "black"),
          axis.ticks.x = element_line(size = 1))
t.test(fatty_acid_omega_oxidation_score~affinity, gcb_np_integrated@meta.data %>% filter(affinity %in% c("High_affinity", "Low_affinity")))

## fatty acid oxidation
fatty_acid_oxidation_gene <- read.csv("signature_gene/fatty_acid_oxidation_gene.csv", header = TRUE, stringsAsFactors = FALSE)
fatty_acid_oxidation_gene <- fatty_acid_oxidation_gene$Gene
fatty_acid_oxidation_ctrl <- get_controls(counts = normalized_matrix,
                                          gene.list = fatty_acid_oxidation_gene)
fatty_acid_oxidation_score <- colMeans(normalized_matrix[fatty_acid_oxidation_gene, ], na.rm = T)-colMeans(normalized_matrix[fatty_acid_oxidation_ctrl, ], na.rm = T)
gcb_np_integrated <- AddMetaData(gcb_np_integrated,
                                  fatty_acid_oxidation_score,
                                  "fatty_acid_oxidation_score")
gcb_np_integrated@meta.data %>%
    filter(affinity %in% c("High_affinity", "Low_affinity")) %>%
    mutate(affinity=factor(affinity, levels = c("Low_affinity", "High_affinity"))) %>%
    ggplot(aes(affinity, fatty_acid_oxidation_score, color = affinity)) +
    geom_boxplot(size=1) +
    scale_color_manual(values = c("#3C5488FF", "#E64B35FF")) +
    theme(panel.background = element_rect(fill = "white"),
          axis.line = element_line(colour = "black"),
          axis.ticks.x = element_line(size = 1))
t.test(fatty_acid_oxidation_score~affinity, gcb_np_integrated@meta.data %>% filter(affinity %in% c("High_affinity", "Low_affinity")))

## fatty acid alpha oxidation
fatty_acid_alpha_oxidation_gene <- read.csv("signature_gene/fatty_acid_alpha_oxidation_gene.csv", header = TRUE, stringsAsFactors = FALSE)
fatty_acid_alpha_oxidation_gene <- fatty_acid_alpha_oxidation_gene$Gene
fatty_acid_alpha_oxidation_ctrl <- get_controls(counts = normalized_matrix,
                                                gene.list = fatty_acid_alpha_oxidation_gene)
fatty_acid_alpha_oxidation_score <- colMeans(normalized_matrix[fatty_acid_alpha_oxidation_gene, ], na.rm = T)-colMeans(normalized_matrix[fatty_acid_alpha_oxidation_ctrl, ], na.rm = T)
gcb_np_integrated <- AddMetaData(gcb_np_integrated,
                                  fatty_acid_alpha_oxidation_score,
                                  "fatty_acid_alpha_oxidation_score")
gcb_np_integrated@meta.data %>%
    filter(affinity %in% c("High_affinity", "Low_affinity")) %>%
    mutate(affinity=factor(affinity, levels = c("Low_affinity", "High_affinity"))) %>%
    ggplot(aes(affinity, fatty_acid_alpha_oxidation_score, color = affinity)) +
    geom_boxplot(size=1) +
    scale_color_manual(values = c("#3C5488FF", "#E64B35FF")) +
    theme(panel.background = element_rect(fill = "white"),
          axis.line = element_line(colour = "black"),
          axis.ticks.x = element_line(size = 1))
t.test(fatty_acid_alpha_oxidation_score~affinity, gcb_np_integrated@meta.data %>% filter(affinity %in% c("High_affinity", "Low_affinity")))

## negative regulation of fatty omega oxidation
negative_regulation_fatty_acid_oxidation_gene <- read.csv("signature_gene/negative_regulation_fatty_acid_oxidation_gene.csv", header = TRUE, stringsAsFactors = FALSE)
negative_regulation_fatty_acid_oxidation_gene <- negative_regulation_fatty_acid_oxidation_gene$Gene
negative_regulation_fatty_acid_oxidation_ctrl <- get_controls(counts = normalized_matrix,
                                                              gene.list = negative_regulation_fatty_acid_oxidation_gene)
negative_regulation_fatty_acid_oxidation_score <- colMeans(normalized_matrix[negative_regulation_fatty_acid_oxidation_gene, ], na.rm = T)-colMeans(normalized_matrix[negative_regulation_fatty_acid_oxidation_ctrl, ], na.rm = T)
gcb_np_integrated <- AddMetaData(gcb_np_integrated,
                                  negative_regulation_fatty_acid_oxidation_score,
                                  "negative_regulation_fatty_acid_oxidation_score")
gcb_np_integrated@meta.data %>%
    filter(affinity %in% c("High_affinity", "Low_affinity")) %>%
    mutate(affinity=factor(affinity, levels = c("Low_affinity", "High_affinity"))) %>%
    ggplot(aes(affinity, negative_regulation_fatty_acid_oxidation_score, color = affinity)) +
    geom_boxplot(size=1) +
    scale_color_manual(values = c("#3C5488FF", "#E64B35FF")) +
    theme(panel.background = element_rect(fill = "white"),
          axis.line = element_line(colour = "black"),
          axis.ticks.x = element_line(size = 1))
t.test(negative_regulation_fatty_acid_oxidation_score~affinity, gcb_np_integrated@meta.data %>% filter(affinity %in% c("High_affinity", "Low_affinity")))

## positive regulation of fatty omega oxidation
positive_regulation_fatty_acid_oxidation_gene <- read.csv("signature_gene/positive_regulation_fatty_acid_oxidation_gene.csv", header = TRUE, stringsAsFactors = FALSE)
positive_regulation_fatty_acid_oxidation_gene <- positive_regulation_fatty_acid_oxidation_gene$Gene
positive_regulation_fatty_acid_oxidation_ctrl <- get_controls(counts = normalized_matrix,
                                                              gene.list = positive_regulation_fatty_acid_oxidation_gene)
positive_regulation_fatty_acid_oxidation_score <- colMeans(normalized_matrix[positive_regulation_fatty_acid_oxidation_gene, ], na.rm = T)-colMeans(normalized_matrix[positive_regulation_fatty_acid_oxidation_ctrl, ], na.rm = T)
gcb_np_integrated <- AddMetaData(gcb_np_integrated,
                                  positive_regulation_fatty_acid_oxidation_score,
                                  "positive_regulation_fatty_acid_oxidation_score")
gcb_np_integrated@meta.data %>%
    filter(affinity %in% c("High_affinity", "Low_affinity")) %>%
    mutate(affinity=factor(affinity, levels = c("Low_affinity", "High_affinity"))) %>%
    ggplot(aes(affinity, positive_regulation_fatty_acid_oxidation_score, color = affinity)) +
    geom_boxplot(size=1) +
    scale_color_manual(values = c("#3C5488FF", "#E64B35FF")) +
    theme(panel.background = element_rect(fill = "white"),
          axis.line = element_line(colour = "black"),
          axis.ticks.x = element_line(size = 1))
t.test(positive_regulation_fatty_acid_oxidation_score~affinity, gcb_np_integrated@meta.data %>% filter(affinity %in% c("High_affinity", "Low_affinity")))

## high affinity gene
high_affinity_gene <- read.csv("signature_gene/high_affinity_gene.csv", header = TRUE, stringsAsFactors = FALSE)
high_affinity_gene <- high_affinity_gene$Gene
high_affinity_ctrl <- get_controls(counts = normalized_matrix,
                                   gene.list = high_affinity_gene)
high_affinity_score <- colMeans(normalized_matrix[high_affinity_gene, ], na.rm = T)-colMeans(normalized_matrix[high_affinity_ctrl, ], na.rm = T)
gcb_np_integrated <- AddMetaData(gcb_np_integrated,
                                 high_affinity_score,
                                 "high_affinity_score")
gcb_np_integrated@meta.data %>%
    filter(affinity %in% c("High_affinity", "Low_affinity")) %>%
    mutate(affinity=factor(affinity, levels = c("Low_affinity", "High_affinity"))) %>% 
    ggplot(aes(affinity, high_affinity_score, color = affinity)) +
    geom_violin(draw_quantiles=c(0.25,0.75), trim = F) +
    geom_quasirandom(size = 0.01, alpha = 0.5) +
    stat_summary(fun.y=mean, geom="point", shape=18, size=3, color="black") +
    scale_color_manual(values = c("#3C5488FF", "#E64B35FF")) +
    theme(panel.background = element_rect(fill = "white"),
          axis.line = element_line(colour = "black"),
          axis.ticks.x = element_line(size = 1))

t.test(high_affinity_score~affinity, gcb_np_integrated@meta.data %>% filter(affinity %in% c("High_affinity", "Low_affinity")))

## low affinity gene
low_affinity_gene <- read.csv("signature_gene/low_affinity_gene.csv", header = TRUE, stringsAsFactors = FALSE)
low_affinity_gene <- low_affinity_gene$Gene
low_affinity_ctrl <- get_controls(counts = normalized_matrix,
                                   gene.list = low_affinity_gene)
low_affinity_score <- colMeans(normalized_matrix[low_affinity_gene, ], na.rm = T)-colMeans(normalized_matrix[low_affinity_ctrl, ], na.rm = T)
gcb_np_integrated <- AddMetaData(gcb_np_integrated,
                                 low_affinity_score,
                                 "low_affinity_score")
gcb_np_integrated@meta.data %>%
    filter(affinity %in% c("High_affinity", "Low_affinity")) %>%
    mutate(affinity=factor(affinity, levels = c("Low_affinity", "High_affinity"))) %>% 
    ggplot(aes(affinity, low_affinity_score, color = affinity)) +
    geom_violin(draw_quantiles=c(0.25,0.75), trim = F) +
    geom_quasirandom(size = 0.01, alpha = 0.5) +
    stat_summary(fun.y=mean, geom="point", shape=18, size=3, color="black") +
    scale_color_manual(values = c("#3C5488FF", "#E64B35FF")) +
    theme(panel.background = element_rect(fill = "white"),
          axis.line = element_line(colour = "black"),
          axis.ticks.x = element_line(size = 1))

t.test(low_affinity_score~affinity, gcb_np_integrated@meta.data %>% filter(affinity %in% c("High_affinity", "Low_affinity")))

## Glutamine metabolic GO:0006541
glutamine_metabolic_gene <- read.csv("signature_gene/glutamine_metabolic_gene.csv", 
                                     header = TRUE, 
                                     stringsAsFactors = FALSE)
glutamine_metabolic_gene <- unique(glutamine_metabolic_gene$Gene)
glutamine_metabolic_gene <- input_gene_filter(normalized_matrix,
                                              glutamine_metabolic_gene)
glutamine_metabolic_ctrl <- get_controls(counts = normalized_matrix,
                                         gene.list = glutamine_metabolic_gene)
glutamine_metabolic_score <- colMeans(normalized_matrix[glutamine_metabolic_gene, ], na.rm = T) -
    colMeans(normalized_matrix[glutamine_metabolic_ctrl, ], na.rm = T)
gcb_np_integrated <- AddMetaData(gcb_np_integrated,
                                 glutamine_metabolic_score,
                                 "glutamine_metabolic_score")
## high vs low affinity 
## total
gcb_np_integrated@meta.data %>%
    filter(affinity %in% c("High_affinity", "Low_affinity")) %>%
    mutate(affinity=factor(affinity, levels = c("Low_affinity", "High_affinity"))) %>% 
    ggplot(aes(affinity, glutamine_metabolic_score, color = affinity)) +
    geom_violin(draw_quantiles=c(0.25,0.75), trim = FALSE, width = 1) +
    geom_quasirandom(dodge.width = 1, size=0.01, alpha = 0.5) +
    stat_summary(fun.y=mean, geom="point", shape=18, size=2, position = position_dodge(width = 1), color = "black") +
    scale_color_manual(values = c("#3C5488FF", "#E64B35FF")) +
    theme(panel.background = element_rect(fill = "white"),
          axis.line = element_line(colour = "black"),
          axis.ticks.x = element_line(size = 1))
t.test(glutamine_metabolic_score~affinity, gcb_np_integrated@meta.data %>%
           filter(affinity %in% c("High_affinity", "Low_affinity")))

## by cluster
gcb_np_integrated@meta.data %>%
    filter(affinity %in% c("High_affinity", "Low_affinity")) %>%
    mutate(affinity=factor(affinity, levels = c("Low_affinity", "High_affinity"))) %>% 
    ggplot(aes(seurat_clusters, glutamine_metabolic_score, color = affinity, group = interaction(seurat_clusters, affinity))) +
    geom_violin(draw_quantiles=c(0.25,0.75), trim = FALSE, width = 1) +
    geom_quasirandom(dodge.width = 1, size=0.01, width = 0.1, alpha = 0.5) +
    stat_summary(fun.y=mean, geom="point", shape=18, size=2, position = position_dodge(width = 1), color = "black") +
    scale_color_manual(values = c("#3C5488FF", "#E64B35FF")) +
    theme(panel.background = element_rect(fill = "white"),
          axis.line = element_line(colour = "black"),
          axis.ticks.x = element_line(size = 1))

fit <- aov(glutamine_metabolic_score ~ seurat_clusters*affinity, 
           gcb_np_integrated@meta.data %>% 
               filter(seurat_clusters!=6,
                      affinity %in% c("Low_affinity", "High_affinity"))) 
summary(fit)
gcb_np_integrated@meta.data %>% 
    filter(seurat_clusters!=6,
           affinity %in% c("Low_affinity", "High_affinity")) %>% 
    mutate(affinity = factor(affinity, levels = c("Low_affinity", "High_affinity"))) %>% 
    group_by(seurat_clusters) %>% 
    wilcox_test(glutamine_metabolic_score~affinity) %>% 
    adjust_pvalue(method = "BH")

## CD40L up common 
cd40l_up_common_gene <- read.csv("signature_gene/cd40l_up_common_gene.csv", 
                                 header = TRUE, 
                                 stringsAsFactors = FALSE)
cd40l_up_common_gene <- unique(cd40l_up_common_gene$Gene)
cd40l_up_common_gene <- input_gene_filter(normalized_matrix,
                                          cd40l_up_common_gene)
cd40l_up_common_ctrl <- get_controls(counts = normalized_matrix,
                                     gene.list = cd40l_up_common_gene)
cd40l_up_common_score <- colMeans(normalized_matrix[cd40l_up_common_gene, ], na.rm = T) -
    colMeans(normalized_matrix[cd40l_up_common_ctrl, ], na.rm = T)
gcb_np_integrated <- AddMetaData(gcb_np_integrated,
                                 cd40l_up_common_score,
                                 "cd40l_up_common_score")
## high vs low affinity 
## total
gcb_np_integrated@meta.data %>%
    filter(affinity %in% c("High_affinity", "Low_affinity")) %>%
    mutate(affinity=factor(affinity, levels = c("Low_affinity", "High_affinity"))) %>% 
    ggplot(aes(affinity, cd40l_up_common_score, color = affinity)) +
    geom_violin(draw_quantiles=c(0.25,0.75), trim = FALSE, width = 1) +
    geom_quasirandom(dodge.width = 1, size=0.01, alpha = 0.5) +
    stat_summary(fun.y=mean, geom="point", shape=18, size=2, position = position_dodge(width = 1), color = "black") +
    scale_color_manual(values = c("#3C5488FF", "#E64B35FF")) +
    theme(panel.background = element_rect(fill = "white"),
          axis.line = element_line(colour = "black"),
          axis.ticks.x = element_line(size = 1))
t.test(cd40l_up_common_score~affinity, gcb_np_integrated@meta.data %>%
           filter(affinity %in% c("High_affinity", "Low_affinity")))

## by cluster
gcb_np_integrated@meta.data %>%
    filter(affinity %in% c("High_affinity", "Low_affinity")) %>%
    mutate(affinity=factor(affinity, levels = c("Low_affinity", "High_affinity"))) %>% 
    ggplot(aes(seurat_clusters, cd40l_up_common_score, color = affinity, group = interaction(seurat_clusters, affinity))) +
    geom_violin(draw_quantiles=c(0.25,0.75), trim = FALSE, width = 1) +
    geom_quasirandom(dodge.width = 1, size=0.01, width = 0.1, alpha = 0.5) +
    stat_summary(fun.y=mean, geom="point", shape=18, size=2, position = position_dodge(width = 1), color = "black") +
    scale_color_manual(values = c("#3C5488FF", "#E64B35FF")) +
    theme(panel.background = element_rect(fill = "white"),
          axis.line = element_line(colour = "black"),
          axis.ticks.x = element_line(size = 1))

fit <- aov(cd40l_up_common_score ~ seurat_clusters*affinity, 
           gcb_np_integrated@meta.data %>% 
               filter(seurat_clusters!=6,
                      affinity %in% c("Low_affinity", "High_affinity"))) 
summary(fit)
gcb_np_integrated@meta.data %>% 
    filter(seurat_clusters!=6,
           affinity %in% c("Low_affinity", "High_affinity")) %>% 
    mutate(affinity = factor(affinity, levels = c("Low_affinity", "High_affinity"))) %>% 
    group_by(seurat_clusters) %>% 
    wilcox_test(cd40l_up_common_score~affinity) %>% 
    adjust_pvalue(method = "BH")

## CD40L up unique 
cd40l_up_unique_gene <- read.csv("signature_gene/cd40l_up_unique_gene.csv", 
                                 header = TRUE, 
                                 stringsAsFactors = FALSE)
cd40l_up_unique_gene <- unique(cd40l_up_unique_gene$Gene)
cd40l_up_unique_gene <- input_gene_filter(normalized_matrix,
                                          cd40l_up_unique_gene)
cd40l_up_unique_ctrl <- get_controls(counts = normalized_matrix,
                                     gene.list = cd40l_up_unique_gene)
cd40l_up_unique_score <- colMeans(normalized_matrix[cd40l_up_unique_gene, ], na.rm = T) -
    colMeans(normalized_matrix[cd40l_up_unique_ctrl, ], na.rm = T)
gcb_np_integrated <- AddMetaData(gcb_np_integrated,
                                 cd40l_up_unique_score,
                                 "cd40l_up_unique_score")
## high vs low affinity 
## total
gcb_np_integrated@meta.data %>%
    filter(affinity %in% c("High_affinity", "Low_affinity")) %>%
    mutate(affinity=factor(affinity, levels = c("Low_affinity", "High_affinity"))) %>% 
    ggplot(aes(affinity, cd40l_up_unique_score, color = affinity)) +
    geom_violin(draw_quantiles=c(0.25,0.75), trim = FALSE, width = 1) +
    geom_quasirandom(dodge.width = 1, size=0.01, alpha = 0.5) +
    stat_summary(fun.y=mean, geom="point", shape=18, size=2, position = position_dodge(width = 1), color = "black") +
    scale_color_manual(values = c("#3C5488FF", "#E64B35FF")) +
    theme(panel.background = element_rect(fill = "white"),
          axis.line = element_line(colour = "black"),
          axis.ticks.x = element_line(size = 1))
t.test(cd40l_up_unique_score~affinity, gcb_np_integrated@meta.data %>%
           filter(affinity %in% c("High_affinity", "Low_affinity")))

## by cluster
gcb_np_integrated@meta.data %>%
    filter(affinity %in% c("High_affinity", "Low_affinity")) %>%
    mutate(affinity=factor(affinity, levels = c("Low_affinity", "High_affinity"))) %>% 
    ggplot(aes(seurat_clusters, cd40l_up_unique_score, color = affinity, group = interaction(seurat_clusters, affinity))) +
    geom_violin(draw_quantiles=c(0.25,0.75), trim = FALSE, width = 1) +
    geom_quasirandom(dodge.width = 1, size=0.01, width = 0.1, alpha = 0.5) +
    stat_summary(fun.y=mean, geom="point", shape=18, size=2, position = position_dodge(width = 1), color = "black") +
    scale_color_manual(values = c("#3C5488FF", "#E64B35FF")) +
    theme(panel.background = element_rect(fill = "white"),
          axis.line = element_line(colour = "black"),
          axis.ticks.x = element_line(size = 1))

fit <- aov(cd40l_up_unique_score ~ seurat_clusters*affinity, 
           gcb_np_integrated@meta.data %>% 
               filter(seurat_clusters!=6,
                      affinity %in% c("Low_affinity", "High_affinity"))) 
summary(fit)
gcb_np_integrated@meta.data %>% 
    filter(seurat_clusters!=6,
           affinity %in% c("Low_affinity", "High_affinity")) %>% 
    mutate(affinity = factor(affinity, levels = c("Low_affinity", "High_affinity"))) %>% 
    group_by(seurat_clusters) %>% 
    wilcox_test(cd40l_up_unique_score~affinity) %>% 
    adjust_pvalue(method = "BH")

## CD40L up combine 
cd40l_up_combine_gene <- read.csv("signature_gene/cd40l_up_combine_gene.csv", 
                                 header = TRUE, 
                                 stringsAsFactors = FALSE)
cd40l_up_combine_gene <- unique(cd40l_up_combine_gene$Gene)
cd40l_up_combine_gene <- input_gene_filter(normalized_matrix,
                                          cd40l_up_combine_gene)
cd40l_up_combine_ctrl <- get_controls(counts = normalized_matrix,
                                     gene.list = cd40l_up_combine_gene)
cd40l_up_combine_score <- colMeans(normalized_matrix[cd40l_up_combine_gene, ], na.rm = T) -
    colMeans(normalized_matrix[cd40l_up_combine_ctrl, ], na.rm = T)
gcb_np_integrated <- AddMetaData(gcb_np_integrated,
                                 cd40l_up_combine_score,
                                 "cd40l_up_combine_score")
## high vs low affinity 
## total
gcb_np_integrated@meta.data %>%
    filter(affinity %in% c("High_affinity", "Low_affinity")) %>%
    mutate(affinity=factor(affinity, levels = c("Low_affinity", "High_affinity"))) %>% 
    ggplot(aes(affinity, cd40l_up_combine_score, color = affinity)) +
    geom_violin(draw_quantiles=c(0.25,0.75), trim = FALSE, width = 1) +
    geom_quasirandom(dodge.width = 1, size=0.01, alpha = 0.5) +
    stat_summary(fun.y=mean, geom="point", shape=18, size=2, position = position_dodge(width = 1), color = "black") +
    scale_color_manual(values = c("#3C5488FF", "#E64B35FF")) +
    theme(panel.background = element_rect(fill = "white"),
          axis.line = element_line(colour = "black"),
          axis.ticks.x = element_line(size = 1))
t.test(cd40l_up_combine_score~affinity, gcb_np_integrated@meta.data %>%
           filter(affinity %in% c("High_affinity", "Low_affinity")))

## by cluster
gcb_np_integrated@meta.data %>%
    filter(affinity %in% c("High_affinity", "Low_affinity")) %>%
    mutate(affinity=factor(affinity, levels = c("Low_affinity", "High_affinity"))) %>% 
    ggplot(aes(seurat_clusters, cd40l_up_combine_score, color = affinity, group = interaction(seurat_clusters, affinity))) +
    geom_violin(draw_quantiles=c(0.25,0.75), trim = FALSE, width = 1) +
    geom_quasirandom(dodge.width = 1, size=0.01, width = 0.1, alpha = 0.5) +
    stat_summary(fun.y=mean, geom="point", shape=18, size=2, position = position_dodge(width = 1), color = "black") +
    scale_color_manual(values = c("#3C5488FF", "#E64B35FF")) +
    theme(panel.background = element_rect(fill = "white"),
          axis.line = element_line(colour = "black"),
          axis.ticks.x = element_line(size = 1))

fit <- aov(cd40l_up_combine_score ~ seurat_clusters*affinity, 
           gcb_np_integrated@meta.data %>% 
               filter(seurat_clusters!=6,
                      affinity %in% c("Low_affinity", "High_affinity"))) 
summary(fit)
gcb_np_integrated@meta.data %>% 
    filter(seurat_clusters!=6,
           affinity %in% c("Low_affinity", "High_affinity")) %>% 
    mutate(affinity = factor(affinity, levels = c("Low_affinity", "High_affinity"))) %>% 
    group_by(seurat_clusters) %>% 
    wilcox_test(cd40l_up_combine_score~affinity) %>% 
    adjust_pvalue(method = "BH")

########
## Sigature by cluster
## oxidative phosphrylation
gcb_np_integrated@meta.data %>%
    filter(seurat_clusters!=6) %>%
    ggplot(aes(seurat_clusters, oxp_score, color = seurat_clusters)) +
    geom_violin(draw_quantiles=c(0.25,0.75)) +
    geom_quasirandom(size = 0.01, width = 0.3, alpha = 0.5) +
    stat_summary(fun.y=mean, geom="point", shape=18, size=3, color="black") +
    theme(panel.grid.major = element_blank(), 
          panel.grid.minor = element_blank(), 
          panel.background = element_blank(), 
          panel.border = element_rect(fill = NA))
fit <- aov(oxp_score ~ seurat_clusters, gcb_np_integrated@meta.data %>% filter(seurat_clusters!=6))
TukeyHSD(fit)

## glycolysis
gcb_np_integrated@meta.data %>%
    filter(seurat_clusters!=6) %>%
    ggplot(aes(seurat_clusters, glycolysis_score, color = seurat_clusters)) +
    geom_violin(draw_quantiles=c(0.25,0.75)) +
    geom_quasirandom(size = 0.01, width = 0.3, alpha = 0.5) +
    stat_summary(fun.y=mean, geom="point", shape=18, size=3, color="black") +
    theme(panel.grid.major = element_blank(), 
          panel.grid.minor = element_blank(), 
          panel.background = element_blank(), 
          panel.border = element_rect(fill = NA))
fit <- aov(glycolysis_score ~ seurat_clusters, gcb_np_integrated@meta.data %>% filter(seurat_clusters!=6))
TukeyHSD(fit)

## fatty acid beta oxidation
gcb_np_integrated@meta.data %>%
    filter(seurat_clusters!=6) %>%
    ggplot(aes(seurat_clusters, fatty_acid_beta_oxidation_score, color = seurat_clusters)) +
    geom_violin(draw_quantiles=c(0.25,0.75)) +
    geom_quasirandom(size = 0.01, width = 0.3, alpha = 0.5) +
    stat_summary(fun.y=mean, geom="point", shape=18, size=3, color="black") +
    theme(panel.grid.major = element_blank(), 
          panel.grid.minor = element_blank(), 
          panel.background = element_blank(), 
          panel.border = element_rect(fill = NA))
fit <- aov(fatty_acid_beta_oxidation_score ~ seurat_clusters, gcb_np_integrated@meta.data %>% filter(seurat_clusters!=6))
TukeyHSD(fit)

## fatty acid omega oxidation
gcb_np_integrated@meta.data %>%
    filter(seurat_clusters!=6) %>%
    ggplot(aes(seurat_clusters, fatty_acid_omega_oxidation_score, color = seurat_clusters)) +
    geom_violin(draw_quantiles=c(0.25,0.75)) +
    geom_quasirandom(size = 0.01, width = 0.3, alpha = 0.5) +
    stat_summary(fun.y=mean, geom="point", shape=18, size=3, color="black") +
    theme(panel.grid.major = element_blank(), 
          panel.grid.minor = element_blank(), 
          panel.background = element_blank(), 
          panel.border = element_rect(fill = NA))
fit <- aov(fatty_acid_omega_oxidation_score ~ seurat_clusters, gcb_np_integrated@meta.data %>% filter(seurat_clusters!=6))
TukeyHSD(fit)

## fatty acid oxidation
gcb_np_integrated@meta.data %>%
    filter(seurat_clusters!=6) %>%
    ggplot(aes(seurat_clusters, fatty_acid_oxidation_score, color = seurat_clusters)) +
    geom_violin(draw_quantiles=c(0.25,0.75)) +
    geom_quasirandom(size = 0.01, width = 0.3, alpha = 0.5) +
    stat_summary(fun.y=mean, geom="point", shape=18, size=3, color="black") +
    theme(panel.grid.major = element_blank(), 
          panel.grid.minor = element_blank(), 
          panel.background = element_blank(), 
          panel.border = element_rect(fill = NA))
fit <- aov(fatty_acid_oxidation_score ~ seurat_clusters, gcb_np_integrated@meta.data %>% filter(seurat_clusters!=6))

## fatty acid alpha oxidation
gcb_np_integrated@meta.data %>%
    filter(seurat_clusters!=6) %>%
    ggplot(aes(seurat_clusters, fatty_acid_alpha_oxidation_score, color = seurat_clusters)) +
    geom_violin(draw_quantiles=c(0.25,0.75)) +
    geom_quasirandom(size = 0.01, width = 0.3, alpha = 0.5) +
    stat_summary(fun.y=mean, geom="point", shape=18, size=3, color="black") +
    theme(panel.grid.major = element_blank(), 
          panel.grid.minor = element_blank(), 
          panel.background = element_blank(), 
          panel.border = element_rect(fill = NA))
fit <- aov(fatty_acid_alpha_oxidation_score ~ seurat_clusters, gcb_np_integrated@meta.data %>% filter(seurat_clusters!=6))

## negative regulation of fatty acid oxidation
gcb_np_integrated@meta.data %>%
    filter(seurat_clusters!=6) %>%
    ggplot(aes(seurat_clusters, negative_regulation_fatty_acid_oxidation_score, color = seurat_clusters)) +
    geom_violin(draw_quantiles=c(0.25,0.75)) +
    geom_quasirandom(size = 0.01, width = 0.3, alpha = 0.5) +
    stat_summary(fun.y=mean, geom="point", shape=18, size=3, color="black") +
    theme(panel.grid.major = element_blank(), 
          panel.grid.minor = element_blank(), 
          panel.background = element_blank(), 
          panel.border = element_rect(fill = NA))
fit <- aov(negative_regulation_fatty_acid_oxidation_score ~ seurat_clusters, gcb_np_integrated@meta.data %>% filter(seurat_clusters!=6))

## positive regulation of fatty omega oxidation
gcb_np_integrated@meta.data %>%
    filter(seurat_clusters!=6) %>%
    ggplot(aes(seurat_clusters, positive_regulation_fatty_acid_oxidation_score, color = seurat_clusters)) +
    geom_violin(draw_quantiles=c(0.25,0.75)) +
    geom_quasirandom(size = 0.01, width = 0.3, alpha = 0.5) +
    stat_summary(fun.y=mean, geom="point", shape=18, size=3, color="black") +
    theme(panel.grid.major = element_blank(), 
          panel.grid.minor = element_blank(), 
          panel.background = element_blank(), 
          panel.border = element_rect(fill = NA))
fit <- aov(positive_regulation_fatty_acid_oxidation_score ~ seurat_clusters, gcb_np_integrated@meta.data %>% filter(seurat_clusters!=6))

## ribosome biogenesis GO:0042254
ribosome_biogenesis_gene <- read.csv("signature_gene/ribosome_biogenesis_gene.csv", header = TRUE, stringsAsFactors = FALSE)
ribosome_biogenesis_gene <- ribosome_biogenesis_gene$Gene
ribosome_biogenesis_ctrl <- get_controls(counts = normalized_matrix, gene.list = ribosome_biogenesis_gene)
ribosome_biogenesis_score <- colMeans(normalized_matrix[ribosome_biogenesis_gene, ], na.rm = T)-colMeans(normalized_matrix[ribosome_biogenesis_ctrl, ], na.rm = T)
gcb_np_integrated <- AddMetaData(gcb_np_integrated,
                                 ribosome_biogenesis_score,
                                 "ribosome_biogenesis_score")
gcb_np_integrated@meta.data %>%
    filter(seurat_clusters!=6) %>%
    ggplot(aes(seurat_clusters, ribosome_biogenesis_score, color = seurat_clusters)) +
    geom_violin(draw_quantiles=c(0.25,0.75)) +
    geom_quasirandom(size = 0.01, width = 0.3, alpha = 0.5) +
    stat_summary(fun.y=mean, geom="point", shape=18, size=3, color="black") +
    theme(panel.grid.major = element_blank(), 
          panel.grid.minor = element_blank(), 
          panel.background = element_blank(), 
          panel.border = element_rect(fill = NA)) 
fit <- aov(ribosome_biogenesis_score ~ seurat_clusters, gcb_np_integrated@meta.data %>% filter(seurat_clusters!=6))


########
## MYC
## myc up
myc_up_gene <- read.csv("signature_gene/myc_up_gene.csv", header = TRUE, stringsAsFactors = FALSE)
myc_up_gene <- myc_up_gene$Symbol
myc_up_ctrl <- get_controls(counts = normalized_matrix, gene.list = myc_up_gene)
myc_up_score <- colMeans(normalized_matrix[myc_up_gene, ], na.rm = T)-colMeans(normalized_matrix[myc_up_ctrl, ], na.rm = T)
gcb_np_integrated <- AddMetaData(gcb_np_integrated,
                                  myc_up_score,
                                  "myc_up_score")
gcb_np_integrated@meta.data %>%
    filter(seurat_clusters!=6) %>%
    ggplot(aes(seurat_clusters, myc_up_score, color = seurat_clusters)) +
    geom_violin(draw_quantiles=c(0.25,0.75)) +
    geom_quasirandom(size = 0.01, width = 0.3, alpha = 0.5) +
    stat_summary(fun.y=mean, geom="point", shape=18, size=3, color="black") +
    theme(panel.grid.major = element_blank(), 
          panel.grid.minor = element_blank(), 
          panel.background = element_blank(), 
          panel.border = element_rect(fill = NA)) 
fit <- aov(myc_up_score ~ seurat_clusters, gcb_np_integrated@meta.data %>% filter(seurat_clusters!=6))

## myc down
myc_down_gene <- read.csv("signature_gene/myc_down_gene.csv", header = TRUE, stringsAsFactors = FALSE)
myc_down_gene <- myc_down_gene$Symbol
myc_down_ctrl <- get_controls(counts = normalized_matrix, gene.list = myc_down_gene)
myc_down_score <- colMeans(normalized_matrix[myc_down_gene, ], na.rm = T)-colMeans(normalized_matrix[myc_down_ctrl, ], na.rm = T)
gcb_np_integrated <- AddMetaData(gcb_np_integrated,
                                 myc_down_score,
                                 "myc_down_score")
gcb_np_integrated@meta.data %>%
    filter(seurat_clusters!=6) %>%
    ggplot(aes(seurat_clusters, myc_down_score, color = seurat_clusters)) +
    geom_violin(draw_quantiles=c(0.25,0.75)) +
    geom_quasirandom(size = 0.01, width = 0.3, alpha = 0.5) +
    stat_summary(fun.y=mean, geom="point", shape=18, size=3, color="black") +
    theme(panel.grid.major = element_blank(), 
          panel.grid.minor = element_blank(), 
          panel.background = element_blank(), 
          panel.border = element_rect(fill = NA))
fit <- aov(myc_down_score ~ seurat_clusters, gcb_np_integrated@meta.data %>% filter(seurat_clusters!=6))

## DANG_MYC_TARGETS_UP
myc_dang_up_gene <- read.csv("signature_gene/myc_dang_up_gene.csv", header = TRUE, stringsAsFactors = FALSE)
myc_dang_up_gene <- myc_dang_up_gene$Symbol
myc_dang_up_ctrl <- get_controls(counts = normalized_matrix, gene.list = myc_dang_up_gene)
myc_dang_up_score <- colMeans(normalized_matrix[myc_dang_up_gene, ], na.rm = T)-colMeans(normalized_matrix[myc_dang_up_ctrl, ], na.rm = T)
gcb_np_integrated <- AddMetaData(gcb_np_integrated,
                                 myc_dang_up_score,
                                 "myc_dang_up_score")
gcb_np_integrated@meta.data %>%
    filter(seurat_clusters!=6) %>%
    ggplot(aes(seurat_clusters, myc_dang_up_score, color = seurat_clusters)) +
    geom_violin(draw_quantiles=c(0.25,0.75)) +
    geom_quasirandom(size = 0.01, width = 0.3, alpha = 0.5) +
    stat_summary(fun.y=mean, geom="point", shape=18, size=3, color="black") +
    theme(panel.grid.major = element_blank(), 
          panel.grid.minor = element_blank(), 
          panel.background = element_blank(), 
          panel.border = element_rect(fill = NA))
fit <- aov(myc_dang_up_score ~ seurat_clusters, gcb_np_integrated@meta.data %>% filter(seurat_clusters!=6))

## HALLMARK_MYC_TARGETS_V1
myc_hallmark_target_gene <- read.csv("signature_gene/myc_hallmark_target_gene.csv", header = TRUE, stringsAsFactors = FALSE)
myc_hallmark_target_gene <- myc_hallmark_target_gene$Symbol
myc_hallmark_target_ctrl <- get_controls(counts = normalized_matrix, gene.list = myc_hallmark_target_gene)
myc_hallmark_target_score <- colMeans(normalized_matrix[myc_hallmark_target_gene, ], na.rm = T)-colMeans(normalized_matrix[myc_hallmark_target_ctrl, ], na.rm = T)
gcb_np_integrated <- AddMetaData(gcb_np_integrated,
                                 myc_hallmark_target_score,
                                 "myc_hallmark_target_score")
gcb_np_integrated@meta.data %>%
    filter(seurat_clusters!=6) %>%
    ggplot(aes(seurat_clusters, myc_hallmark_target_score, color = seurat_clusters)) +
    geom_violin(draw_quantiles=c(0.25,0.75)) +
    geom_quasirandom(size = 0.01, width = 0.3, alpha = 0.5) +
    stat_summary(fun.y=mean, geom="point", shape=18, size=3, color="black") +
    theme(panel.grid.major = element_blank(), 
          panel.grid.minor = element_blank(), 
          panel.background = element_blank(), 
          panel.border = element_rect(fill = NA)) 
fit <- aov(myc_hallmark_target_score ~ seurat_clusters, gcb_np_integrated@meta.data %>% filter(seurat_clusters!=6))

